# Site settings
title: Yeoun Yi [yʌun i]
short_logo: Yeoun Yi [yʌun i]
description: >
  Studying NLP or Computational Linguistics. Interested in Advertising. 
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yeounyi.github.io" # the base hostname & protocol for your site

author:
  fullname: Yeoun Yi
  github: yeounyi
  linkedin: yeoun-yi-989360166/
  email: yeounyi@gmail.com

disqus_name: https-yeounyi-github-io
g_track_id: 

markdown: kramdown

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Yeoun Yi
      author_link: <a href="https://yeounyi.github.io">Yeoun Yi<a>
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
